### ISSUE TITLE
Offsets: add spectral drop detector?

### ISSUE THREAD

**Issue by cannam** [cannam/expressive-means#1]
From email:

> Finally, one last suggestion regarding offset detector: To compensate for quiet passages with no much difference between attack maximum and offset, could we give it a try to combine the raw power drop logic with a spectral drop detector for upper overtone frequencies?
>
> That is, an offset is defined either if the raw power level falls [level drop threshold] below sustain begin level or if all frequencies between 2 and 5 kHz apparent at sustain begin fall below [new parameter, preset: -70 dB].
>
> To improve transparency for the user, these parameters could be renamed „Offset sensitivity: Raw power drop threshold“ and „Offset sensitivity: Spectral drop threshold“.

**Comment by FrithjofVollmer** [comment]
Just found that the spectral floor threshold discussed in https://github.com/cannam/expressive-means/issues/1#issuecomment-1413844876 apparently affects other spectrum-related measurements as well – for instance, if set to -76 instead -70 dBFS, onsets are identified as being far more noisy as they are (which let's me assume that the parameter currently has a global effect). 

– is this inevitable, or is there a way to relate this floor parameter to offset detection only? Thank you!

**Comment by cannam** [comment]
That's right, there is only a single noise floor threshold and the spectral levels are only calculated once, which is when that threshold is applied. Features based on that threshold, e.g. offset detection and articulation noise, just query the number of bins above threshold that were found when the calculation first happened.

To change this we could do one of the following

1. have two separate thresholds explicitly calculated within the single `SpectralLevelRise` calculator - the easiest and least intrusive solution but a little bit conceptually iffy because it gives `SpectralLevelRise` more logic that probably ought to belong to the code that uses it (i.e. it's a leaky abstraction)
2. stop doing thresholding at all within the first pass of `SpectralLevelRise`, instead save the full magnitude history and make it possible to query the bins above any given threshold at any point in the history subsequently - conceptually cleaner and also fairly easy to do but with somewhat greater overhead in memory use and therefore also a bit unsatisfying
3. use two separate `SpectralLevelRise` objects for the different purposes, one for offsets and the other for noise - conceptually very clean, but slower as `SpectralLevelRise` handles the whole frequency-domain pipeline itself, potentially fiddly because of the requirement to provide consistent parameter sets to both, and a more intrusive change

None of these is totally satisfactory, but I'd probably go for option 2.

(You are not required to have an opinion!)

**Comment by cannam** [comment]
Update: option 2 is non-causal (see discussion in #23) so let's not introduce another non-causal element at this point. I'll go for option 1 instead I think.

**Comment by cannam** [comment]
OK, fixed in be18003. The "Spectral drop floor level" parameter now controls only the offset level, not the level used for noise floor for noisy onset classification. They both default to -70dB but there is no parameter controlling the latter, so it's effectively fixed.

**Comment by FrithjofVollmer** [comment]
Great, thank you...!
