### ISSUE TITLE
Pitch Vibrato: debug options? 

### ISSUE THREAD

**Issue by FrithjofVollmer** [cannam/expressive-means#16]
Hi Chris, 

found a short time window + sufficient Wifi in a German train to have a first look into the vibrato summary output. The layout looks great so far, thanks a lot! Regarding the analysis itself: do you think, there may be some more options again for debugging (or would it take too much time)? 

Take the first few bars of the Huberman example for instance: Based on manual measurement, they signify as 
4Fn> / N / 4Fm> / N / N ... – instead it currently returns: 

<img width="1512" alt="Screenshot 2023-04-01 at 15 57 34" src="https://user-images.githubusercontent.com/122092828/229294553-1a502485-e38f-49d1-a4f0-60ed7de4c256.png">

...so at first glance it seems to me that the detectors for 

1) _Duration_ (start / end of the vibrato) and _Rate_ – that is, the number of peaks recognised – are too insensitive so far (for these aspects, the "peak" debug helps a lot already, thanks!), 
2) _Range_ seem to me way too sensitive (almost all Huberman vibratos are analysed as being "wide" [w] instead of "narrow"],
3) _Development_ almost always return "stable" [=] instead of "decreasing" [>] (this changes only with very large vibratos, as in the Roehn example)

Anyways, will have a deeper look into this on Tuesday! Thanks, so far!

**Comment by cannam** [comment]
This last change is in the repository now, and also in the 0.1.1 release.

**Comment by FrithjofVollmer** [comment]
This works just great. Thanks a lot. Issue (finally) solved!
