### ISSUE TITLE
Pitch detection switch 

### ISSUE THREAD

**Issue by FrithjofVollmer** [cannam/expressive-means#25]
(future work:) 

Pitch detection doesn't makes sense when using the onset detectors for piano music (as the spectral rise detector has a far better performance here) or, in particular, for percussion. Bridged the problem temporarily by setting absurdly high pitch sensitivity parameter values as defaults. However, (especially) when working with the "advanced" outputs, a simple switch to bypass pitch detection would presumably be a clearly more preferable and elegant option...

**Comment by FrithjofVollmer** [comment]
Also see #28 beforehand, please!

**Comment by cannam** [comment]
Although this was labelled for "future work", I didn't like the idea of shipping a 1.0 with "temporary hack" parameter settings such that an existing parameter specification may become incompatible with future updates. So I have had a go at this one - please test.

**Comment by FrithjofVollmer** [comment]
Very cool, thanks a lot (also for implementation in the Semantic outputs already)...! This is tested now, issue cleared.
