### ISSUE TITLE
Vibrato elements within IOI

### ISSUE THREAD

**Issue by cannam** [cannam/expressive-means#29]
From email:

> We discussed at an early stage that if there are multiple vibrato elements within an IOI that are separated from each other (leaving a gap in between), only the succession closest to the onset should be considered. We tried to compensate for onset-crossing instances this way.
> Now it turns out that, while we addressed the problem by means of the „segmented“ and „without glide“ modes sufficiently, this rule returns significantly incomplete results when it comes to singing in particular. Would it therefore be conceivable to tell the plugin to count all vibrato elements detected within an IOI (but to leave out the gap when it comes to rate calculation, of course)?

I think an example might be useful - this looks like a fiddly one to implement without a test case.

**Comment by FrithjofVollmer** [comment]
Yes, here it is (from the "1960 Ella_Misty (Ausschnitt)_voice only" sample, at 1.845): 

<img width="2560" alt="Screenshot 2023-06-22 at 12 15 00" src="https://github.com/cannam/expressive-means/assets/122092828/684f477b-2c81-4132-bd0e-6a53bf9a3938">

...the Vibrato Only Pitch Track indicates to successions of vibrato elements: a short one at the beginning (which actually is a false positive) and a long one at the end (from 2.281 on). Currently, the "Type" and "Index" outputs consider the first one only.

Other problematic occurrences are at 8.225 and 10.135, where "Vibrato Only" identifies vibrato elements, but they are not at all considered for the "Summary" (and "Type" + "Index") outputs. Do you have an idea why that could be?

<img width="2560" alt="Screenshot 2023-06-22 at 12 22 19" src="https://github.com/cannam/expressive-means/assets/122092828/4e65b22a-7126-4438-aea6-5a230cac1d4b">

**Comment by cannam** [comment]
The reason the vibrato at 8.225+ is not attached to the previous onset is that the previous onset has an *offset* before the vibrato begins. (Check the Onsets plugin's "durations" output)

**Comment by cannam** [comment]
The same is the case in the long note starting at 1.764 - see picture. This shows onsets, note durations, and vibrato-only pitch track calculated by the current build of Semantic plugins using jazz vocal preset, along with note offsets calculated with the advanced onset plugin in which I manually set the parameters to match that preset (since there is no semantic offset output).

There is a power rise onset at 1.764, but then a spectral drop offset is detected at 1.976, long before the vibrato even begins!

![Screenshot_20230717_163224](https://github.com/cannam/expressive-means/assets/104933/ae293f91-83ba-48c2-b564-0e09f62be397)

**Comment by FrithjofVollmer** [comment]
Ah, right, thanks a lot! As this seems to be a matter of sensitivity then, I tested a few alternatives. The problem here seems to me a general voice-specific one, due to a number of things: 1) Noisy onsets (due to, e.g., breathing or consonants) lap the notes' sustain phases more than in instrumental playing; 2) the transition of vocals to voiced consonants (e.g., from an [a] to an [m]) leads to a significant loss of overtones wich falsely prompts an spectral drop offset; (3) tiny portamentos at the beginning of the notes lead to 'wrong' reference frequencies for spectral drop offset identification.   

So I suggest there are two ways to handle this: 
- either to make the "spectral drop ratio" threshold a parameter and set it remarkably lower (this would be the clean option I guess), e.g., to 0.2 for all Vocal presets (for beginners, will test), or 
- to change the sustain begin as well as the spectral drop parameters for Vocals only. However, this would help for a few instances only (but not the ones mentioned above) and come at the cost of a raised number of false-negative offsets. 

What do you think? I would probably prefer a combination of both...

**Comment by cannam** [comment]
Your analysis seems about right to me! I think the first option sounds sensible.

**Comment by FrithjofVollmer** [comment]
Cool, thanks! (Also, is there a way to implement something like „if sustain phase begins in the middle of a glide, reset it starting at glide end“? 

Glide logic is already implemented in Vibrato anyways, right? *Edit:* Sorry, this is for the common offset detection branch of course, as it should affect Articulation as well)

**Comment by cannam** [comment]
So looking at the code, it appears the spectral drop ratio is entirely hard coded at the moment, to 0.4. (CoreFeatures.cpp line 774) Should be straightforward enough to make a parameter out of that.

> Glide logic is already implemented in Vibrato anyways, right? Edit: Sorry, this is for the common offset detection branch of course, as it should affect Articulation as well

Right, and there is no reference to glides available at that point in the calculation. Perhaps the requirement could be framed somehow in terms of the pitch onset detection function, which is available there and is quite closely related?

**Comment by cannam** [comment]
Spectral drop offset ratio is now a parameter in e962c3a

I haven't added it to the semantic adapters since I'm not sure which settings should affect it  - can you handle that part? The parameter is named `spectralDropOffsetRatio` and it is a percentage, so the default is 40 rather than 0.4.

**Comment by FrithjofVollmer** [comment]
**future work:**

> Perhaps the requirement could be framed somehow in terms of the pitch onset detection function, which is available there and is quite closely related?

...sounds good to me! Anyways, let's bridge this for now by a slightly increased "sustain begin" default? Will do this (and the testing) tonight.

**Comment by FrithjofVollmer** [comment]
> I haven't added it to the semantic adapters since I'm not sure which settings should affect it - can you handle that part?

This is implemented and tested now – think we are good to go for v1.0, I guess...?!
