### ISSUE TITLE
Decide what to do with the various debug outputs

### ISSUE THREAD

**Issue by cannam** [cannam/expressive-means#8]
This is an issue for tracking any thoughts about the various "Debug" outputs that we have.

We probably ought to make a choice, for each of them:

 * Is it useful enough to be promoted to an "official" output for the plugin?
 * Is it useful, but perhaps something that should be in a different plugin altogether? We already moved some of the debug stuff from Articulation into the new Onset plugin, and if desired we could make further plugins to return other intermediate features
 * Or is it not all that useful, so that for later release builds we can switch off the `WITH_DEBUG_OUTPUTS` flag in the code and just hide it along with the other development outputs (or even remove it altogether)

No urgency to this, we can rearrange things at the end, and perhaps as we go through the remaining plugins we'll find other things that they have in common (as with Onsets). But if you have any thoughts as we go, jot them down here.

**Comment by FrithjofVollmer** [comment]
...think this issue is cleared now; the selection of outputs to me seems very reasonable now... :)
